language: python
os:
  - osx
  - linux
before_install:
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then;
    brew update;
    brew install openssl readline;
    brew outdated pyenv || brew upgrade pyenv;
    brew install pyenv-virtualenv;
    pyenv install $PYTHON;
    export PYENV_VERSION=$PYTHON;
    export PATH="/Users/travis/.pyenv/shims:${PATH}";
    pyenv-virtualenv venv;
    source venv/bin/activate;
    python --version;
  fi
python:
  - "3.6"
script:
  - python -m unittest
