language: generic
os:
  - osx
python:
  - "3.6"
before_install:
  - brew update
  - brew install python3
  - brew install boost-python
  - virtualenv env -p python3
  - source env/bin/activate
  - echo $PYTHON
install:
  - python setup.py install
script:
  - python -m unittest
